pv:
  economic_lifetime: 30
  wacc: 0.044
  conservative:
    capex: 912
    fixed_om: 12
    variable_om: 0
  moderate:
    capex: 700
    fixed_om: 10
    variable_om: 0
  advanced:
    capex: 520
    fixed_om: 8
    variable_om: 0

onshore:
  economic_lifetime: 30
  wacc: 0.05
  conservative:
    capex: 900
    fixed_om: 41
    variable_om: 0
  moderate:
    capex: 760
    fixed_om: 33
    variable_om: 0
  advanced:
    capex: 525
    fixed_om: 24
    variable_om: 0

offshore:
  economic_lifetime: 30
  wacc: 0.052
  conservative:
    capex: 2817
    fixed_om: 94
    variable_om: 0
  moderate:
    capex: 1945
    fixed_om: 71
    variable_om: 0
  advanced:
    capex: 1583
    fixed_om: 61
    variable_om: 0
