[server]
runOnSave = true

[browser]
gatherUsageStats = false

[theme]
base = "light"
primaryColor = "#dc2626"
backgroundColor = "#f9fafb"
secondaryBackgroundColor = "#f3f4f6"
textColor = "#1e293b"
font = "serif"
